"""
Feature Pipeline Tasks
======================
Airflow task functions for all feature engineering steps.
These are pure Python functions decorated with @task (TaskFlow API).

Each function:
    - Has explicit inputs and outputs (XCom compatible)
    - Handles its own error logging
    - Is independently testable outside Airflow
    - Returns a status dict for downstream tasks to inspect
"""

import os
import sys
import json
from pathlib import Path
from datetime import datetime, timedelta
from loguru import logger

# ---- Path setup so tasks can import project modules ----
RECSYS_SRC = Path(os.getenv("RECSYS_SRC", "/opt/airflow/recsys_src"))
sys.path.insert(0, str(RECSYS_SRC / "feature_store"))
sys.path.insert(0, str(RECSYS_SRC / "training"))


# ----------------------------------------------------------------
# TASK 1: Load CSVs → PostgreSQL
# ----------------------------------------------------------------

def task_load_features_to_postgres(**context) -> dict:
    """
    Loads enriched feature CSVs into PostgreSQL tables.

    Upstream:  data/raw/*.csv (generated by data generator)
    Downstream: Feast feature views (PostgreSQLSource)

    Returns:
        dict with row counts for each table loaded
    """
    logger.info("TASK: load_features_to_postgres started")

    try:
        # Import here so Airflow worker can find it
        sys.path.insert(0, str(RECSYS_SRC / "feature_store"))
        from load_features_to_postgres import FeaturePostgresLoader

        loader = FeaturePostgresLoader()
        loader.load_all()
        loader.verify()

        result = {
            "status":    "success",
            "timestamp": datetime.utcnow().isoformat(),
            "tables":    ["item_features_raw", "user_features_raw"],
        }

        logger.success("TASK: load_features_to_postgres completed")
        return result

    except Exception as e:
        logger.error(f"TASK: load_features_to_postgres FAILED: {e}")
        raise   # Re-raise so Airflow marks task as failed


# ----------------------------------------------------------------
# TASK 2: Apply Feast Registry
# ----------------------------------------------------------------

def task_feast_apply(**context) -> dict:
    """
    Runs 'feast apply' to register/update all feature definitions.

    This ensures the registry reflects any schema changes
    made to entities.py, feature_views.py, or feature_services.py.

    Equivalent to: cd feature_repo && feast apply
    """
    logger.info("TASK: feast_apply started")

    try:
        from feast import FeatureStore

        repo_path = os.getenv(
            "FEAST_REPO_PATH",
            str(RECSYS_SRC / "feature_store" / "feature_repo")
        )

        store = FeatureStore(repo_path=repo_path)
        store.apply([])  # Discovers and applies all definitions

        # List what was registered
        views    = store.list_feature_views()
        entities = store.list_entities()

        result = {
            "status":         "success",
            "timestamp":      datetime.utcnow().isoformat(),
            "feature_views":  [v.name for v in views],
            "entities":       [e.name for e in entities],
        }

        logger.success(
            f"TASK: feast_apply completed | "
            f"views={[v.name for v in views]} | "
            f"entities={[e.name for e in entities]}"
        )
        return result

    except Exception as e:
        logger.error(f"TASK: feast_apply FAILED: {e}")
        raise


# ----------------------------------------------------------------
# TASK 3: Full Materialization → Redis
# ----------------------------------------------------------------

def task_materialize_features(
    start_date_str: str = None,
    **context
) -> dict:
    """
    Materializes features from PostgreSQL offline store to Redis.
    Auto-detects the data range from PostgreSQL if no start_date given.
    """
    logger.info("TASK: materialize_features started")

    try:
        from feast import FeatureStore
        from sqlalchemy import create_engine, text as sql_text

        repo_path = os.getenv(
            "FEAST_REPO_PATH",
            str(RECSYS_SRC / "feature_store" / "feature_repo")
        )

        store = FeatureStore(repo_path=repo_path)
        end_date = datetime.utcnow()

        if start_date_str:
            start_date = datetime.fromisoformat(start_date_str)
        else:
            # Auto-detect earliest timestamp from PostgreSQL
            pg_user = os.getenv("POSTGRES_USER", "recsys_user")
            pg_pass = os.getenv("POSTGRES_PASSWORD", "recsys_password")
            pg_host = os.getenv("POSTGRES_HOST", "postgres")
            pg_port = os.getenv("POSTGRES_PORT", "5432")
            pg_db   = os.getenv("FEAST_DB", "feast_db")
            engine = create_engine(
                f"postgresql+psycopg2://{pg_user}:{pg_pass}"
                f"@{pg_host}:{pg_port}/{pg_db}"
            )
            with engine.connect() as conn:
                row = conn.execute(
                    sql_text(
                        "SELECT MIN(event_timestamp) "
                        "FROM feast.user_features_raw"
                    )
                ).fetchone()
            start_date = row[0] if row and row[0] else datetime(2020, 1, 1)
            # Remove timezone if present (Feast materialize expects naive or consistent tz)
            if hasattr(start_date, 'tzinfo') and start_date.tzinfo:
                start_date = start_date.replace(tzinfo=None)

        logger.info(
            f"Materializing | "
            f"start={start_date} | "
            f"end={end_date}"
        )

        store.materialize(
            start_date=start_date,
            end_date=end_date,
        )

        result = {
            "status":     "success",
            "timestamp":  datetime.utcnow().isoformat(),
            "start_date": start_date.isoformat(),
            "end_date":   end_date.isoformat(),
            "mode":       "full",
        }

        logger.success("TASK: materialize_features completed")
        return result

    except Exception as e:
        logger.error(f"TASK: materialize_features FAILED: {e}")
        raise
    
# ----------------------------------------------------------------
# TASK 4: Incremental Materialization
# ----------------------------------------------------------------

def task_materialize_incremental(**context) -> dict:
    """
    Incrementally materializes only new features since last run.
    Used by the 6-hourly feature refresh DAG.
    More efficient than full materialization for frequent runs.
    """
    logger.info("TASK: materialize_incremental started")

    try:
        from feast import FeatureStore

        repo_path = os.getenv(
            "FEAST_REPO_PATH",
            str(RECSYS_SRC / "feature_store" / "feature_repo")
        )

        store    = FeatureStore(repo_path=repo_path)
        end_date = datetime.utcnow()

        store.materialize_incremental(end_date=end_date)

        result = {
            "status":    "success",
            "timestamp": datetime.utcnow().isoformat(),
            "end_date":  end_date.isoformat(),
            "mode":      "incremental",
        }

        logger.success("TASK: materialize_incremental completed")
        return result

    except Exception as e:
        logger.error(f"TASK: materialize_incremental FAILED: {e}")
        raise


# ----------------------------------------------------------------
# TASK 5: Verify Redis Population
# ----------------------------------------------------------------

def task_verify_redis(**context) -> dict:
    """
    Sanity check — verifies Redis contains feature data after
    materialization. Fails the DAG if Redis is empty.
    """
    logger.info("TASK: verify_redis started")

    try:
        import redis as redis_lib

        r = redis_lib.Redis(
            host     = os.getenv("REDIS_HOST", "redis"),
            port     = int(os.getenv("REDIS_PORT", "6379")),
            db       = 0,
            password = os.getenv("REDIS_PASSWORD", "") or None,
        )

        key_count  = r.dbsize()
        ping_ok    = r.ping()

        if key_count == 0:
            raise ValueError(
                "Redis is EMPTY after materialization. "
                "Check Feast offline store has data."
            )

        result = {
            "status":    "success",
            "timestamp": datetime.utcnow().isoformat(),
            "redis_keys": key_count,
            "redis_ping": ping_ok,
        }

        logger.success(
            f"TASK: verify_redis completed | "
            f"keys={key_count:,} | ping={ping_ok}"
        )
        return result

    except Exception as e:
        logger.error(f"TASK: verify_redis FAILED: {e}")
        raise